Tchpnki 2.29 ajax
frontend-park-mail-ru/2022_2_Technopanki pull request #13
Opened 2022-10-31 22:04 UTC by VladislavKirpichov

2022-11-04 21:34 UTC, Victorius19 requested changes
Накинул пару комментов

2022-11-04 21:34 UTC, Victorius19 commented on src/lib/network.ts
> +        };
Этот код повторяется 4 раза? *недвусмысленный намек на отдельный приватный метод*

2022-11-04 21:34 UTC, Victorius19 commented on src/lib/network.ts
> +        };
(В get можно просто payload пустым оставлять)

2022-11-04 21:34 UTC, Victorius19 commented on src/services/signInService.ts
> +        [],
Зачем передавать пустой массив в хеадерс? Думаю этот аргумент будет редко использоваться, можно тупо его сделать таким же не обязательным как и credentials

2022-11-04 21:34 UTC, Victorius19 commented on src/utils/constants.ts
> +export const SIGN_IN_URL = 'api/sign-in/';
Вероятно чтобы не заводить огромный зоопарк различных констант, можно будет в будущем просто создать набор нескольких enum для различных типов запросов к беку

2022-11-04 21:34 UTC, Victorius19 commented on src/utils/validation/messages.ts
> +export const DEFAULT_MESSAGE = 'Ошибка. Проверьте email или пароль';
Аналогично вероятно лучше делать enum

2022-11-05 12:23 UTC, somnevaetsya requested changes
Я в принципе не особо понял, что вообще происходит, но написал

2022-11-05 12:23 UTC, somnevaetsya commented on src/lib/network.ts
> +        console.info(`GET request. URL: ${url}`);
Каждый вывод в консоль увеличивает время работы твоего приложения, ну я так, к слову

2022-11-05 12:23 UTC, somnevaetsya commented on src/services/signInService.ts
> +        [],
Согласен

2022-11-05 12:23 UTC, somnevaetsya commented on src/services/signUpService.ts
> +            email: formData.get('email'),
У нас должны модельки жестко вот тут? Нельзя отдельный пакет сделать?

2022-11-05 12:23 UTC, somnevaetsya commented on src/utils/constants.ts
> +export const SIGN_IN_URL = 'api/sign-in/';
Вероятно, можно даже сделать конфиг, на случай, если у нас что-то поменялось, а не искать вот в этом файлике, вот в этой папочке, вот на этой строчечке

2022-11-05 12:23 UTC, somnevaetsya commented on src/utils/validation/formValidation.ts
> +export const setInvalidServerResponse = (event: SubmitEvent, responseBody) => {
ООООО

2022-11-05 12:23 UTC, somnevaetsya commented on src/views/SignIn/SignIn.tsx
>                          <div key={'inputs'} className={'flex column g-16'}>
У нас html должен быть внутри js? Точно?

2022-11-05 21:19 UTC, Zuhropenchik approved these changes

2022-11-08 21:33 UTC, merged