Tchpnki merge
frontend-park-mail-ru/2022_2_Technopanki pull request #16
Opened 2022-11-10 16:36 UTC by VladislavKirpichov

2022-11-10 22:10 UTC, Victorius19 requested changes
^_^

2022-11-10 22:10 UTC, Victorius19 commented on src/services/employerProfileService.ts
> +        //         }
комменты

2022-11-10 22:10 UTC, Victorius19 commented on src/services/employerProfileService.ts
> +            )
еще комменты

2022-11-10 22:10 UTC, Victorius19 commented on src/static/index.html
> +    <script type="module" src="http://95.163.208.72:8000/js/main.js"></script>
айпишкни.....
Сделай константу которая будет доставать url фронта

2022-11-10 22:10 UTC, Victorius19 commented on src/store/resume/actions.ts
> +}
\ n

2022-11-10 22:10 UTC, Victorius19 commented on src/store/resume/store.ts
> +);
\n

2022-11-10 22:10 UTC, Victorius19 commented on src/views/Employer/userPage.module.scss
> +}
\n

2022-11-10 22:10 UTC, Victorius19 commented on src/views/Vacancies/vacancies.module.scss
> +}
\n

2022-11-10 22:10 UTC, Victorius19 commented on src/views/Vacancy/VacancyHat.tsx
> +
комменты

2022-11-10 22:10 UTC, Victorius19 commented on src/views/Vacancy/VacancySettings.tsx
> +                                'http://95.163.208.72:8000/image/employer.png'
айпи

2022-11-10 22:19 UTC, Zuhropenchik approved these changes

2022-11-11 11:03 UTC, Victorius19 approved these changes

2022-11-11 11:03 UTC, merged