Tchpnki 4.4 notifications
frontend-park-mail-ru/2022_2_Technopanki pull request #26
Opened 2022-12-16 18:20 UTC by sonichka-s

2022-12-17 20:37 UTC, Victorius19 requested changes
Все в целом норм, но не забывай запускать линтер

2022-12-17 20:37 UTC, Victorius19 commented on src/components/TextLink/link.module.scss
> +}
\n

2022-12-17 20:37 UTC, Victorius19 commented on src/components/TextLink/TextLink.tsx
> +let counter = 0;
Что это?

2022-12-17 20:37 UTC, Victorius19 commented on src/components/UI-kit/buttons/LongButton.tsx
> +}
\n

2022-12-17 20:37 UTC, Victorius19 commented on src/components/UI-kit/buttons/LongButton.tsx
> +                )}
Лучше запихнуть условие в шаблонную строку, это уберет дублирование кода

2022-12-17 20:37 UTC, Victorius19 commented on src/components/UI-kit/header/Header.tsx
> +        nextProps: Readonly<{ userType: string, id: string }> | { userType: string, id: string },
{ userType: string, id: string } повторяется в коде три раза, стоит вынести в отдельный тип

2022-12-17 20:37 UTC, Victorius19 commented on src/components/UI-kit/notifications/NotificationCard.tsx
> +    // }
Комменты

2022-12-17 20:37 UTC, Victorius19 commented on src/components/UI-kit/notifications/NotificationCard.tsx
> +                                            Фронтенд-разработчик
Этот код пока не используется? Еще же нет события на скачивание резюме

2022-12-17 20:37 UTC, Victorius19 commented on src/components/UI-kit/notifications/NotificationCard.tsx
> +}
\n

2022-12-17 20:37 UTC, Victorius19 commented on src/components/UI-kit/notifications/NotificationsWindow.tsx
> +        })
Где ;?

2022-12-17 20:37 UTC, Victorius19 commented on src/components/UI-kit/notifications/NotificationsWindow.tsx
> +        }))
;

2022-12-17 20:37 UTC, Victorius19 commented on src/components/UI-kit/notifications/NotificationsWindow.tsx
> +        }))
Линтер стоит запускать

2022-12-17 20:37 UTC, Victorius19 commented on src/components/UI-kit/notifications/NotificationsWindow.tsx
> +                    <div className={'pt-5'} onClick={() => console.log('click')}>
лишний onClick

2022-12-17 20:37 UTC, Victorius19 commented on src/components/UI-kit/notifications/NotificationsWindow.tsx
> +                                                // companyID={}
Коменты

2022-12-17 20:37 UTC, Victorius19 commented on src/components/UI-kit/notifications/NotificationsWindow.tsx
> +}
\n

2022-12-17 20:37 UTC, Victorius19 commented on src/components/UI-kit/notifications/notifications.module.scss
> +}
\n

2022-12-17 20:37 UTC, Victorius19 commented on src/lib/network.ts
> +        // protocols?: string[]
коммент

2022-12-17 20:37 UTC, Victorius19 commented on src/services/notificationService.ts
> +import network from "../lib/network"
линтер

2022-12-17 20:37 UTC, Victorius19 commented on src/store/notification/reducer.ts
> +};
\n

2022-12-18 15:19 UTC, sonichka-s commented on src/components/UI-kit/notifications/NotificationCard.tsx
> +                                            Фронтенд-разработчик
Да, но в скоро будет

2022-12-19 13:33 UTC, merged