Tchpnki 8 components signup+auth
frontend-park-mail-ru/2022_2_Technopanki pull request #3
Opened 2022-09-29 21:03 UTC by VladislavKirpichov

2022-09-29 22:15 UTC, Victorius19 requested changes
Есть пару комментов

2022-09-29 22:15 UTC, Victorius19 commented on src/lib/core/Root.js
> +}
Не вижу смысла в этом классе. Зачем в нем реализовывать логику приложения, которая должна быть реализована в самом роутере?

2022-09-29 22:15 UTC, Victorius19 commented on src/lib/core/Root.js
> +        this.#root = root;
Зачем тут записывается root, если он никогда не используется

2022-09-29 22:15 UTC, Victorius19 commented on src/lib/router/Link.js
> +    };
Это тоже логика роутера, которая лучше реализовывать непосредственно в самом роутере

2022-09-29 22:15 UTC, Victorius19 commented on src/lib/router/Link.js
> +    button.onclick = RouteLink;
Лучше никогда не вешать обработчики на onclick

2022-09-29 22:15 UTC, Victorius19 commented on src/lib/router/Router.js
> +};
Думаю для полноценного роутера никогда не хватит простой функции. Если хочешь сделать сразу нормальный роутер, то давай вынесем всю логику, которая связана с роутером в класс

2022-09-29 22:15 UTC, Victorius19 commented on src/static/index.html
> +<html lang="en">
опять en

2022-09-29 22:15 UTC, Victorius19 commented on src/lib/core/Root.js
> +        });
Этот обработчк точно необходим, если ты используешь pushState?

2022-09-29 22:15 UTC, Victorius19 commented on src/views/Signup.js
> +    const template = Handlebars.compile(signUpTemplate);
Лучше пока как-нибудь компилить handlebars заранее командой, и сюда грузить уже собранные функции. Тогда можно будет избавится от шизойдных файликов с html как строкой

2022-10-01 19:30 UTC, VladislavKirpichov commented on src/lib/core/Root.js
> +        });
Он нужен для перехода по стрелке назад в браузере

2022-10-03 21:28 UTC, Victorius19 requested changes
Прочитать все эти файлы было очень сложно

2022-10-03 21:28 UTC, Victorius19 commented on src/lib/core/VDOM/render.js
> +    // TODO: rework to forEach
Не забудь о TODO, вероятно даже лучше не forEach

2022-10-03 21:28 UTC, Victorius19 commented on src/lib/router/Router.js
> +    routePathMap: {},
Почитай о Map, это новая тема, которая гораздо лучше подойдет для такой задачи, как минимум по тому, что она работает быстрее

2022-10-03 21:28 UTC, Victorius19 commented on src/services/formValidation.js
> +    elem.innerText = message;
Может переписать это сразу на состояния компонента?

2022-10-03 21:28 UTC, Victorius19 commented on src/services/network/signUpHandler.js
> +    console.log(formData.get('toggle'));
лог который в мейн не вольем

2022-10-03 21:28 UTC, Victorius19 commented on src/static/index.html
> +        <title>Jobflow</title>
Добавь мета тег, что я кидал

2022-10-03 21:28 UTC, Victorius19 commented on src/static/index.html
> +    <script src="https://cdn.jsdelivr.net/npm/handlebars@latest/dist/handlebars.js"></script>
оно тут не надо

2022-10-03 21:28 UTC, Victorius19 commented on src/styles/css/auth.css
> +.auth {
Кинь в игнор все css файлы

2022-10-03 21:28 UTC, Victorius19 commented on src/styles/sass/variables.scss
> +$screen-xxlg: 3656px;
\n

2022-10-07 08:10 UTC, Victorius19 approved these changes

2022-10-07 08:31 UTC, Zuhropenchik approved these changes

2022-10-07 09:40 UTC, sonichka-s approved these changes

2022-10-07 09:52 UTC, merged