New VDOM core library + docker file for server.js
frontend-park-mail-ru/2022_2_Technopanki pull request #6
Opened 2022-10-18 21:40 UTC by VladislavKirpichov

2022-10-22 14:22 UTC, Victorius19 requested changes
Все супер! Правда какой-то передоз от ts-ignore, постарайся убрать большую часть

2022-10-22 14:22 UTC, Victorius19 commented on Reacts/reacts-dom/diff/applyDiff.ts
> +        // @ts-ignore
резня

2022-10-22 14:22 UTC, Victorius19 commented on Reacts/reacts-dom/diff/applyDiff.ts
> +        // @ts-ignore
тоже резня

2022-10-22 14:22 UTC, Victorius19 commented on tsconfig.json
> +}
\n

2022-10-22 14:22 UTC, Victorius19 commented on src/App.tsx
> +    }
Какой-то кринж так конструктор прописывать каждый раз

2022-10-22 14:22 UTC, Victorius19 commented on tsconfig.dev.json
> +}
\n

2022-10-28 17:44 UTC, Victorius19 approved these changes

2022-10-28 18:39 UTC, Zuhropenchik approved these changes

2022-10-28 18:41 UTC, merged