Flux
frontend-park-mail-ru/2022_2_Technopanki pull request #8
Opened 2022-10-28 11:48 UTC by VladislavKirpichov

2022-10-28 21:22 UTC, sonichka-s approved these changes

2022-10-30 15:36 UTC, Victorius19 requested changes

2022-10-30 15:36 UTC, Victorius19 commented on Fluxs/store.ts
> +export default class Store<S = any> implements StoreType {
Почему у тебя то, что обычно называется диспетчером, называется стором?

2022-10-30 15:36 UTC, Victorius19 commented on Fluxs/store.ts
> +export default class Store<S = any> implements StoreType {
Также, раз это диспетчер, то почему нет никакого класса самого стора?))

2022-10-30 15:36 UTC, Victorius19 commented on Fluxs/store.ts
> +        this.listeners.forEach(listener => listener());
Что-то у меня мозг начал плавиться от такого решения. Почему бы не передавать action в listener? Ведь по любому там он будет требоваться для того, чтобы понять какое событие было вызвано и придется вызывать еще и getState в самом listener.

2022-10-30 15:51 UTC, VladislavKirpichov commented on Fluxs/store.ts
> +export default class Store<S = any> implements StoreType {
Насчет названия: это объект которые хранит в себе стор и методы работы с ним. Семантически мне кажется понятнее будет, если объект будет называться стором. Например, когда мы создаем его инстанс.

2022-10-30 15:52 UTC, VladislavKirpichov commented on Fluxs/store.ts
> +export default class Store<S = any> implements StoreType {
Стор это по сути S, пользователь сам определяет интерфейс стора

2022-10-30 17:37 UTC, Victorius19 approved these changes

2022-10-30 17:37 UTC, merged